const browserify = require('browserify')
const babelify = require('babelify')

browserify()
  .transform(babelify)
  .plugin('proxyquire-universal')
  .require(require.resolve('../test/basic.spec.js'), { entry: true })
  .require(require.resolve('../test/api.spec.js'), { entry: true })
  .bundle()
  .pipe(process.stdout)
